name: mhs-ci

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-mhs-prettyprinter:
    runs-on: ubuntu-latest
    steps:

    - name: checkout mhs repo
      uses: actions/checkout@v4
      with:
        repository: augustss/MicroHs
        ref: v0.14.27.0
        path: mhs
    - name: make and install mhs
      run: |
        cd mhs
        make minstall

    # prettyprinter
    - name: checkout prettyprinter repo
      uses: actions/checkout@v4
      with:
        path: prettyprinter

    - name: compile and install prettyprinter package
      run: |
        PATH="$HOME/.mcabal/bin:$PATH"
        cd prettyprinter/prettyprinter
        mcabal -r install

    - name: compile and install prettyprinter-ansi-terminal package
      run: |
        PATH="$HOME/.mcabal/bin:$PATH"
        cd prettyprinter/prettyprinter-ansi-terminal
        mcabal -r install

    - name: compile and install prettyprinter-compat-annotated-wl-pprint package
      run: |
        PATH="$HOME/.mcabal/bin:$PATH"
        cd prettyprinter/prettyprinter-compat-annotated-wl-pprint
        mcabal -r install

    - name: compile and install prettyprinter-compat-ansi-wl-pprint package
      run: |
        PATH="$HOME/.mcabal/bin:$PATH"
        cd prettyprinter/prettyprinter-compat-ansi-wl-pprint
        mcabal -r install

    - name: compile and install prettyprinter-compat-wl-pprint package
      run: |
        PATH="$HOME/.mcabal/bin:$PATH"
        cd prettyprinter/prettyprinter-compat-wl-pprint
        mcabal -r install

    - name: cleanup
      run: |
        rm -rf $HOME/.mcabal
